[platformio]
lib_dir = systems

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
build_flags =
    -D USB_SERIAL
    -include Arduino.h
    -std=gnu++17
    -I include ## Required for being able to keep config.h in include whilst having custom folders
monitor_speed = 115200

lib_deps =
    sparkfun/SparkFun u-blox GNSS v3@^3.1.9
    sparkfun/SparkFun Qwiic 6Dof - LSM6DSO@^1.0.2
    adafruit/Adafruit BMP280 Library@^2.6.8
    adafruit/Adafruit Unified Sensor@^1.1.14
    adafruit/Adafruit BusIO@^1.16.1
    xreef/EByte LoRa E32 library@^1.5.13
    https://github.com/adafruit/Adafruit_MLX90393_Library


[env:native]
platform = native
test_framework = unity
build_flags =
    -std=c++17
    -I include ## Required for being able to keep config.h in include whilst having custom folders